name: Build package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
      - uses: actions/upload-artifact@v2
        with:
          name: name-of-artifact
          path: src/dist/windows
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.11"
#          architecture: "x64"
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r src/requirements.txt